ZCutter Class Reference
Originial zenith cutter, from ZCuts99.
#include <ZCutter.h>
Public Member Functions
void applyCorrections (HillasParameterization &p)
void setCamera (int npix, int utdate)
Detailed Description
Originial zenith cutter, from ZCuts99.
Uses SuperCuts-like cuts, but with zenith angle corrections based on cos(theta).
Definition at line 12 of file ZCutter.h.
Member Function Documentation
void ZCutter::applyCorrections (HillasParameterization & param) [virtual]
Perform zenith correction.
Overrides the SuperCutter::prePass() function which is executed before cuts are applied by SuperCutter::pass()
Todo : make sigma_pix and the `0.023` free optimization parameters!
Reimplemented from SuperCutter.
Definition at line 40 of file ZCutter.cpp.
References HillasParameterization::centroid, HillasParameterization::distance, CutInfo::elongation, Camera::getPEToDC(), Camera::getSigmaPixel(), Camera::getSigmaPSF(), HillasParameterization::length, HillasParameterization::length_over_size, HillasParameterization::max, HillasParameterization::miss, HillasParameterization::point_of_origin_a, HillasParameterization::point_of_origin_b, HillasParameterization::size, HillasParameterization::width, Coordinate_t::x, Coordinate_t::y, and HillasParameterization::zenith.
The documentation for this class was generated from the following files:
ZCutter.h
ZCutter.cpp