PlotMaker Class Reference
Plots stuff to any PlotUtils graphics context.
#include <PlotMaker.h>
Classes
struct PlotState
Public Types
enum ColorMap {
COLORMAP_BLUES,
COLORMAP_REDBLUE,
COLORMAP_YELLOWGREEN,
COLORMAP_INVERSEGREY,
COLORMAP_GREY,
COLORMAP_RAINBOW,
COLORMAP_HOT,
COLORMAP_PRINTABLE
 }
enum ContourLineStyle { LINE_SOLID,
LINE_DOTTED,
LINE_DASHED
 }
enum CameraPlotType { CAMERA_IMAGE,
CAMERA_PEDS,
CAMERA_PEDDISPS,
CAMERA_TUBENUMS
 }
Public Member Functions
PlotMaker (std::string type, std::string filename=``, double minx=-3.1, double miny=-3.1, double maxx=3.1, double maxy=3.1)
void setAxisBox (double minx, double miny, double maxx, double maxy)
void setAxisBox (Image2D &im2d)
void setAxisBox (Camera &cam)
void setSpace (double minx, double miny, double maxx, double maxy)
void flush ()
void newPage ()
void pushState ()
void popState ()
void rotate (double theta)
void plotAxes ()
void plotTitle (std::string title)
void plotSubtitle (std::string title)
void plotXTicAt (double x)
void plotYTicAt (double y)
void plotXMinorTicAt (double x)
void plotYMinorTicAt (double y)
void contourPlot (Image2D &im2d, double zmin, double zmax, double dz)
void plotRADecGrid (Image2D &ragrid, Image2D &decgrid)
void plot (Image2D &im2d)
void plot (Camera &cam, const Array_t &image, const vector< Pedestal > &peds, vector< int > &cleanpixels, CameraPlotType plottype=CAMERA_IMAGE)
void plot (HillasParameterization &p)
void plot (MuonParameterization &p)
void plot (Star &s, int symbol=16)
void plot (vector< double > &xpoints, vector< double > &ypoints)
void plot (string text, double x, double y)
void plot (TelescopeArray &array)
void plotEllipse (double x, double y, double r1, double r2, double theta=0)
void plotMarker (double x, double y)
void setColorMap (ColorMap c)
void setColorMap (string name)
void getMappedColor (double value, int &red, int &green, int &blue)
void setPixelScale (double pixscale)
void setScaleFactor (double factor)
void setTicLevel (int l)
void setColorScale (double lower, double upper)
void enableAutoScale (bool val=true)
void setContourColorName (string name)
void setTicMarkColorName (string name)
void setContourLineStyle (ContourLineStyle i)
void setContourLineStyle (string style)
void setContourLineWidth (double width)
void setLabelColorName (string name)
void setLabelAngle (double theta)
void setLabelSize (double size)
void setMarkerType (int type)
void setMarkerSize (double size)
void setMarkerColorName (string name)
Detailed Description
Plots stuff to any PlotUtils graphics context.
Definition at line 19 of file PlotMaker.h.
Member Function Documentation
void PlotMaker::getMappedColor (double value, int & red, int & green, int & blue)
Returns the rgb color for the specified grey value (in range 0..1)
Parameters
value grey value which should be mapped to a color (0..1)
red returned color value (0..65535)
green returned color value (0..65535)
blue returned color value (0..65535)
Definition at line 891 of file PlotMaker.cpp.
void PlotMaker::plotAxes ()
Plot a set of axes around the AxisBox region.
Todo : don't plot minor tics where a major tic is
Definition at line 98 of file PlotMaker.cpp.
Referenced by WUArray::analyzeRun(), Cutter::cut(), and PedestalFinder::getPeds().
The documentation for this class was generated from the following files:
PlotMaker.h
PlotMaker.cpp