Cutter Class Reference
Cuts parameterized data, calculates statistics, and generates final histograms.
#include <Cutter.h>
Public Types
enum types { ON,
OFF,
TRACK
 }
Public Member Functions
void enableOutput (bool val=1)
void enableScaledParameterOutput (bool val=1)
void enableFastImageProcessing (bool val=1)
void enable2D (bool val=1)
void enablePointingCheck (bool val=true)
void enableDisplay (bool val=true)
void process (RunInfo &ri)
RunStatistics getTrackingStatistics (CutRecord &run, double ratio)
RunStatistics getPairStatistics (CutRecord &onrun, CutRecord &offrun)
RunStatistics getTotalPairStatistics ()
void outputStatistics ()
double energyEstimator (double size, double dist)
CutRecord getTotal (std::vector< CutRecord > &)
double maxLikelihoodSignif (double n_on, double n_off, double alpha)
CutRecord cut (RunInfo &, const std::string &, char)
void generateImage (CutRecord &on, CutRecord &off, std::string dir, std::string title, bool finalimage=false)
void radiallyBinPoints (std::vector< Coordinate_t > &poolist, Image2D &destimage, double radius)
void setOutputDir (std::string dirname)
void printCutRecordFields (std::ostream &stream)
void checkPointing ()
void checkDiagnostics ()
double getElongationFactor (double zenith)
void setTelescopeID (int num)
void clear ()
Detailed Description
Cuts parameterized data, calculates statistics, and generates final histograms.
Todo : this is a badly designed class. Cutter should be a small object which applies a specific set of cuts (subclasses for other cutting methods). All the analysis should be done elsewhere.
Todo : For multi-telescope analysis, make a telescope_id argument or field and only process events from the specified telescope.
Definition at line 39 of file Cutter.h.
Member Function Documentation
CutRecord Cutter::cut (RunInfo & , const std::string & , char)
Read the parameterized data for the specified run id and count the number of events that pass the various cuts.
Also generates histograms of rate, size, energy, etc. This function is called by Cutter::process for each run in the configuration file, so there is usually no need to call it directly.
Returns
a CutRecord containing all the totals for the specified run.
Todo : Implement 2-D analysis for tracking runs (currently, only ON/OFF pairs are used.
Todo : separate total alpha plot for tracking runs.
Definition at line 1162 of file Cutter.cpp.
References Image2D::addHist(), CutInfo::align_offset, CutInfo::alignment, HillasParameterization::alpha, SuperCutter::applyCorrections(), HeaderRecord::average_elevation, HillasParameterization::centroid, Image2D::clear(), RunInfo::cuts, RunInfo::cuttype, HeaderRecord::dec, HillasParameterization::distance, HeaderRecord::endtime, HillasParameterization::energy_estimate, RunInfo::energyestimator, StarCatalog::findNearbyStars(), ParamDataReader::getHeaderRecord(), ImageParameterization::gpstime, Histogram::increment(), CutFactory::instance(), EnergyEstimatorFactory::instance(), HeaderRecord::nadc, HeaderRecord::num_telescopes, SuperCutter::pass(), PlotMaker::plotAxes(), HillasParameterization::point_of_origin_a, HillasParameterization::point_of_origin_b, StarCatalog::precessToDate(), HeaderRecord::ra, CutInfo::radial_analysis, CutInfo::radial_offset, Image2D::save(), Image2D::setCoordinateBox(), HillasParameterization::size, CutInfo::smoothing_radius, HeaderRecord::sourcename, HeaderRecord::starttime, ImageParameterization::telescope_id, RunInfo::utbase, RunInfo::utdate, Coordinate_t::x, Coordinate_t::y, and HillasParameterization::zenith.
Referenced by process().
double Cutter::energyEstimator (double size, double dist)
Return the energy estimate for the given size and distance values.
Returns
x = log(Energy)
Definition at line 1664 of file Cutter.cpp.
void Cutter::generateImage (CutRecord & on, CutRecord & off, std::string dir, std::string title, bool finalimage = false)
Save a datafile (image2d-total.dat) containing the 2D excess and significance values for all of the data that has been currently cut.
The format of the output file is 6 columns per line:
column 1: x camera coordinate bin (in degrees)
column 2: y camera coordinate bin (in degrees)
column 3: excess counts
column 4: significance
column 5: Right Ascension of bin
column 6: Declination of bin
Definition at line 832 of file Cutter.cpp.
References Image2D::addHistRadially(), Image2D::addImage(), Image2D::applyRadialSmoothing(), Image2D::expand(), maxLikelihoodSignif(), Image2D::save(), and Image2D::setCoordinateBox().
Referenced by outputStatistics(), and process().
double Cutter::getElongationFactor (double zen)
Returns
zenith angle dependent elongation factor for the camera
Definition at line 1687 of file Cutter.cpp.
double Cutter::maxLikelihoodSignif (double n_on, double n_off, double alpha)
Returns the maximum likelihood significance (see Li and Ma, 1983)
Parameters
n_on number of on-source counts
n_off number of off-source counts
alpha 1/(tracking ratio) for tracking runs, or on/off duration for on/off pairs.
NOTE alpha is defined as 1/(tracking ratio) where the tracking ratio is the ratio of (number of off-source bins)/(on-source bins) So, e.g., for an `alpha` cut of alpha<15 for on-source and 20 < alpha < 65 for off-source, the tracking ratio = 3.0 and alpha = 0.333. Defining alpha in this way, excess = n_on - alpha * n_off.
Definition at line 158 of file Cutter.cpp.
Referenced by generateImage().
void Cutter::process (RunInfo & ri)
Cut the data in the specified run, and build up statistics for all runs.
Each run's cut information is stored in the onruns/offruns/trackruns vectors.
Definition at line 1081 of file Cutter.cpp.
References cut(), RunInfo::cuts, generateImage(), RunInfo::offid, RunInfo::onid, Logger::printf(), CutInfo::radial_analysis, CutInfo::smoothing_radius, and RunInfo::type.
The documentation for this class was generated from the following files:
Cutter.h
Cutter.cpp