Histogram Class Reference
General 1-D histogram class.
#include <Histogram.h>
Public Member Functions
Histogram (int, double, double, std::string)
Histogram (const Histogram &h)
void increment (double)
void accumulate (double x, double weight)
int maxBin ()
int minBin ()
double maxValue ()
double minValue ()
void getRange (int bin, double &lower, double &upper)
double mean ()
double sigma ()
double sum ()
void save (std::string)
void load (std::string)
int findBinWithValue (double val)
void saveStatistics (std::string)
int numBins ()
void scale (double val)
void subtract (Histogram &h)
double operator[] (int)
double get (int bin)
void reset ()
gsl_histogram * getGSLHist ()
Detailed Description
General 1-D histogram class.
Todo : Make this class work with lightcurve data where the first and last bins may be partially filled (or smaller width)
Definition at line 21 of file Histogram.h.
Constructor & Destructor Documentation
Histogram::Histogram (int nbins, double minx, double maxx, std::string name)
Create a new Histogram.
Parameters
numbins number of bins
min minimum value
max maximum value
name description of the histogram
Definition at line 34 of file Histogram.cpp.
Histogram::Histogram (const Histogram & h)
Copy constructor.
Bug : doesn't work yet
Definition at line 71 of file Histogram.cpp.
Member Function Documentation
int Histogram::findBinWithValue (double val)
Returns
index of bin with the specified value, -1 on failure.
Definition at line 351 of file Histogram.cpp.
double Histogram::get (int i) [inline]
Return histogram value at index i.
Can also use the [] operator (i.e. myhist[3] is equivalent to myhist.get(3))
Definition at line 108 of file Histogram.h.
Referenced by Fitter::minimize().
void Histogram::increment (double x) [inline]
Increment the bin corresponding to the specified value.
Implemented as an inline function for speed.
Definition at line 70 of file Histogram.h.
References maxValue(), and minValue().
Referenced by WUArray::analyzeRun(), and Cutter::cut().
void Histogram::load (std::string filename)
Read in a histogram saved with the `save` function.
The histogram to be read must have the number of bins as the Histogram object.
Definition at line 235 of file Histogram.cpp.
double Histogram::mean ()
Returns
the mean value in the histogram.
Definition at line 320 of file Histogram.cpp.
Referenced by saveStatistics().
void Histogram::saveStatistics (std::string)
Write out a text file with statistical info about the histogram.
This function is automatically called when Histogram::save() is called, but is provided separately in case one wants to just write statistics and not the whole histogram. It would be cleaner to append this to the top of the histogram file itself, but that would make it harder for external programs to read the histogram files, so I decided to keep the stats file separate.
Parameters
basename base filename (.hist.stats is appended)
Definition at line 205 of file Histogram.cpp.
References maxBin(), maxValue(), mean(), minBin(), minValue(), sigma(), and sum().
Referenced by Image2D::save().
double Histogram::sigma ()
Returns
the variance in the histogrammed value.
Definition at line 330 of file Histogram.cpp.
Referenced by saveStatistics().
void Histogram::subtract (Histogram & hist)
Subtracts the specified histogram from the current one.
Parameters
hist histogram containing values to subtract. Must have identical bin ranges as the current histogram.
Definition at line 386 of file Histogram.cpp.
double Histogram::sum ()
Returns
the total number of counts in the histogram.
Definition at line 340 of file Histogram.cpp.
Referenced by saveStatistics().
The documentation for this class was generated from the following files:
Histogram.h
Histogram.cpp