GainFinder Class Reference
Retrieve or calculate nitrogen gains, given a nitrogen run ID.
#include <GainFinder.h>
Public Member Functions
void getGains (RunInfo &ri, Array_t &gains, int telescope_id=0)
void setThresholds (double, double, double)
Detailed Description
Retrieve or calculate nitrogen gains, given a nitrogen run ID.
Definition at line 14 of file GainFinder.h.
Member Function Documentation
void GainFinder::getGains (RunInfo & ri, Array_t & gains, int telescope_id = 0)
Fetch the gains for the specified nitrogen run.
Parameters
ri - Run information struct from Config
id - nitrogen gain id
gains - uninitialized Array_t where gains will be stored
Todo : make gains database have a code column which marks bad gains
: implement lock file!
Definition at line 48 of file GainFinder.cpp.
References RunInfo::cachedir, PedestalFinder::getPeds(), RawDataReaderFactory::getReader(), RawDataReaderFactory::instance(), RunInfo::n2id, HeaderRecord::nadc, HeaderRecord::num_telescopes, and PedestalFinder::setTubeOffThresholds().
void GainFinder::setThresholds (double min, double max, double percent)
Set gain cutoff thresholds.
The default values are used if this method is not called explicitly.
Parameters
min - minimim adc value to include in gain calculation (default is 50)
max - maximum adc value to include in gain calculation (default 1000)
percent - percent of camera above which the image is considered `saturated` and should be ignored for gain calculations (default 0.75)
Definition at line 30 of file GainFinder.cpp.
The documentation for this class was generated from the following files:
GainFinder.h
GainFinder.cpp