StarCatalog Class Reference
A searchable star database.
#include <StarCatalog.h>
Public Member Functions
StarCatalog ()
void load (std::string stardbfilename)
void findNearbyStars (double, double, double, std::list< Star > &)
void precessToDate (int utdate)
Detailed Description
A searchable star database.
Definition at line 42 of file StarCatalog.h.
Member Function Documentation
void StarCatalog::findNearbyStars (double , double , double , std::list< Star > &)
Produces a vector of stars that fall within a specified radius of a specified ra+dec coordinate.
Also figures out the position of each star in tangential cartesian coordinates, relative to the center position for easy plotting.
Parameters
ra right ascension where the camera is pointing
dec declination where the camera is pointing
r radius (in degrees) around which to look for stars (should be FOV of camera)
nearbystars empty vector of Stars which will be filled up with the results
Todo : check that this ra and dec from the tracking computer are already precessed, or from j2000 or something. If not already precessed, they need to be.
Definition at line 136 of file StarCatalog.cpp.
Referenced by Cutter::cut().
void StarCatalog::load (std::string stardbfilename)
Load a saved image.
Load a database of stars from the specified .edb file (such as those included with XEphem.
Definition at line 238 of file Image2D.cpp.
References Image2D::setCoordinateBox().
void StarCatalog::precessToDate (int utdate)
Precess star catalog to the current epoch.
Parameters
utdate for example '020506' for May 6, 2002
Todo : Should check this - it looks like stars are moving too much over the course of a year or so, so it's possible this is not working exactly right. However, it's pretty close.
Definition at line 189 of file StarCatalog.cpp.
Referenced by Cutter::cut().
The documentation for this class was generated from the following files:
StarCatalog.h
Image2D.cpp
StarCatalog.cpp