Fitter Class Reference
Class that performs actual chi-square grid search.
#include <Fitter.h>
Public Member Functions
Fitter (RunInfo &ri)
void minimize (EnergySpectrum *energy_on, EnergySpectrum *energy_off, double &N0, double &Gamma0, double &e0, double Time, double n0Range, int n0Step, double gRange, int gStep, double onoffratio)
void save ()
Fitter (RunInfo &ri)
void minimize (EnergySpectrum *energy_on, EnergySpectrum *energy_off, double &N0, double &Gamma0, double &E0, double Time, double n0Range, int n0Step, double gRange, int gStep, double e0Range, double e0Step, double onoffratio)
void save ()
Detailed Description
Class that performs actual chi-square grid search.
Definition at line 172 of file Fitter.h.
Member Function Documentation
void Fitter::minimize (EnergySpectrum * energy_on, EnergySpectrum * energy_off, double & N0, double & Gamma0, double & e0, double Time, double n0Range, int n0Step, double gRange, int gStep, double onoffratio)
Start Actual Fitting Process Save Chi-Square Table in File `Totals/chi.text`.
Todo : put `alpha` or tracking ratio into the onOff and onOffVariance: onoff = on-a*off, variance=a*(on+off) or whatever
Definition at line 333 of file Fitter.cpp.
References Histogram::get(), ProgressBar::print(), and ProgressBar::printClear().
void Fitter::minimize (EnergySpectrum * energy_on, EnergySpectrum * energy_off, double & N0, double & Gamma0, double & E0, double Time, double n0Range, int n0Step, double gRange, int gStep, double e0Range, double e0Step, double onoffratio)
Start Actual Fitting Process Save Chi-Square Table in File `Totals/chi.text`.
Todo : put `alpha` or tracking ratio into the onOff and onOffVariance: onoff = on-a*off, variance=a*(on+off) or whatever
Definition at line 334 of file FitterNew.cpp.
References Histogram::get(), ProgressBar::print(), and ProgressBar::printClear().
The documentation for this class was generated from the following files:
Fitter.h
FitterNew.h
Fitter.cpp
FitterNew.cpp