PedestalFinder Class Reference
Class to generate pedestal values for a series of runs.
#include <PedestalFinder.h>
Public Member Functions
void getOnSourcePeds (RunInfo &ri, std::vector< Pedestal > &ped, int telescope_id=0)
void getOffSourcePeds (RunInfo &ri, std::vector< Pedestal > &ped, int telescope_id=0)
void getPeds (RunInfo &ri, const std::string &id, std::vector< Pedestal > &, int telescope_id=0)
void setTubeOffThresholds (double lower, double upper)
void setBadPedThresh (double value)
Detailed Description
Class to generate pedestal values for a series of runs.
Definition at line 29 of file PedestalFinder.h.
Member Function Documentation
void PedestalFinder::getPeds (RunInfo & ri, const std::string & id, std::vector< Pedestal > & , int telescope_id = 0)
Returns the pedestal values as an array of Pedestal structs.
Todo : Simulations only contain one pedestal record, so their dispersions are always 0. Due to this, the ImageCleaner accepts too many pixels, since it uses the picthresh*peddisp as the threshold! Need to fix somehow...
Todo : implement lockfiles to prevent more than one process from writing/reading to the database (necessary for the MPI-enabled or a multi-threaded version)
Definition at line 67 of file PedestalFinder.cpp.
References RunInfo::cachedir, RawDataReaderFactory::getReader(), RawDataReaderFactory::instance(), RunInfo::max_ped_events, HeaderRecord::nadc, HeaderRecord::num_telescopes, PlotMaker::plotAxes(), ProgressBar::print(), ProgressBar::printClear(), Logger::printf(), and HeaderRecord::windowsize.
Referenced by GainFinder::getGains().
void PedestalFinder::setTubeOffThresholds (double lower, double upper)
Set the thresholds to detect turned off tubes or stars.
Parameters
lower threshold to detect turned off tubes (default is 0.6)
upper threshold to detect stars (default is 1.5)
Definition at line 46 of file PedestalFinder.cpp.
Referenced by GainFinder::getGains().
The documentation for this class was generated from the following files:
PedestalFinder.h
PedestalFinder.cpp