MCSpectrum Class Reference
Object that takes care of all the Monte Carlo (MC) dependent aspects:
#include <Fitter.h>
Public Member Functions
MCSpectrum (RunInfo &ri)
void fill (double N0, double Gamma0, double E0, double Time)
double chiSquare (std::vector< Data > &)
int dof ()
double get (int)
void getRange (int bin, double &lower, double &upper)
EnergySpectrum * getSpectrum ()
MCSpectrum (RunInfo &ri)
void fill (double N0, double Gamma0, double E0, double Time)
double chiSquare (std::vector< Data > &)
int dof ()
double get (int)
void getRange (int bin, double &lower, double &upper)
EnergySpectrum * getSpectrum ()
Static Public Attributes
static const int NUMMCBINS = 9
Detailed Description
Object that takes care of all the Monte Carlo (MC) dependent aspects:
it stores the MC events
given model parameters, it can produce histograms with `artficial` energy spectra that can be compared to the data
given a pointer to the data, and a filled `artificial` energy spectrum, it will compute the chi-square value.
Definition at line 96 of file Fitter.h.
Constructor & Destructor Documentation
MCSpectrum::MCSpectrum (RunInfo & ri)
Creator, gets all the MC information.
Todo : make the specific energy estimator function user selectable (LZA vs small zenith, etc.)
Todo : make the specific energy estimator function user selectable (LZA vs small zenith, etc.)
Definition at line 45 of file Fitter.cpp.
References RunInfo::cuts, HillasParameterization::distance, RunInfo::energyestimator, EnergyEstimatorFactory::instance(), RunInfo::mcdatabase, ProgressBar::print(), ProgressBar::printClear(), ImageParameterization::sim, HillasParameterization::size, and HillasParameterization::zenith.
The documentation for this class was generated from the following files:
Fitter.h
FitterNew.h
Fitter.cpp
FitterNew.cpp