Image2D Class Reference
Representation of a 2-D raster image (for 2D analysis)
#include <Image2D.h>
Public Member Functions
Image2D (int nxbins=39, int nybins=39)
void setCoordinateBox (double minx, double miny, double maxx, double maxy)
double getXCoord (int i)
double getYCoord (int j)
double getMinX ()
double getMinY ()
double getMaxX ()
double getMaxY ()
void load (std::string filename)
void save (std::string filename)
void savePGM (std::string filename)
void saveGrid (std::string filename)
void clear ()
void setPixel (int i, int j, double val)
double getPixel (int i, int j)
void addToPixel (int i, int j, double val)
void addHist (double x, double y, double val)
void addHistRadially (double x, double y, double val, float radius)
int getOutsideHits ()
void addImage (Image2D &im)
void applyRadialSmoothing (double r)
int getXDim ()
int getYDim ()
double minValue ()
double maxValue ()
void getIndexOfMax (int &i, int &j)
void expand ()
Image2D * crossCorrelateWith (Image2D &)
int getXHistBinOf (double x)
int getYHistBinOf (double y)
Detailed Description
Representation of a 2-D raster image (for 2D analysis)
Definition at line 14 of file Image2D.h.
Member Function Documentation
void Image2D::addHist (double x, double y, double val)
Add the specified value to the pixel which contains the coordinate (x,y).
This is useful for histogramming in 2-D.
Definition at line 104 of file Image2D.cpp.
Referenced by Cutter::cut().
void Image2D::addHistRadially (double x, double y, double val, float radius)
Adds the value val to all pixels in the image that are within radius of the point (x,y).
This provides another method to radially smooth an image while filling it. It's slower than calling applyRadialSmoothing() after an image has been created, but it's more accurate.
Todo : can speed this up considerably with geometric considerations (by only iterating over range of pixels that fall withing radius*2 for example)
Definition at line 138 of file Image2D.cpp.
Referenced by WUArray::analyzeRun(), and Cutter::generateImage().
void Image2D::addImage (Image2D & im)
Add another image to this image.
Sums each pixel. Images must be of the same dimensions.
Definition at line 81 of file Image2D.cpp.
Referenced by Cutter::generateImage().
Image2D * Image2D::crossCorrelateWith (Image2D & image)
Compute the cross-corrolation with the specified image.
Returns a new Image2D of the correlation coefficients. Remember to delete the new image when you're done with it.
 C_{ij} = \sum_{k,l} I_1(k,l) * I_2((k+i) mod N,(l+j) mod M) 
Definition at line 536 of file Image2D.cpp.
References setCoordinateBox().
Referenced by Cutter::checkPointing().
void Image2D::save (std::string filename)
Output a tab delimited datafile and corresponding GNUplot file.
Write the image to disk.
Parameters
filename base filename name of output text file (file extension will be added.
We follow the convention that the x-value of the histogram is the value of the lower bound on the corresponding bin. To calculate the value at the center of the bin it is necessary to add half of the bin width.
Definition at line 176 of file Histogram.cpp.
References Histogram::saveStatistics().
Referenced by WUArray::analyzeRun(), Cutter::checkPointing(), Cutter::cut(), and Cutter::generateImage().
void Image2D::setCoordinateBox (double minx, double miny, double maxx, double maxy)
Set up the coordinate values of the image.
Specify the boundaries of the image, not the positions of the center of the boundary pixels!
Definition at line 54 of file Image2D.cpp.
Referenced by WUArray::analyzeRun(), crossCorrelateWith(), Cutter::cut(), expand(), Cutter::generateImage(), and StarCatalog::load().
The documentation for this class was generated from the following files:
Image2D.h
Histogram.cpp
Image2D.cpp