WUArray Namespace Reference
Function prototypes and globals for wuarray.
Enumerations
enum RunType { TRACK,
ON,
OFF
 }
Functions
void showUsage ()
void getCommandLineOptions (int argc, char **argv)
void shutdown ()
void trap_ctrl_c (int)
void process (RunInfo &ri)
void analyzeRun (RunInfo &ri, RunType runtype)
Variables
PlotMaker * pm = NULL
Detailed Description
Function prototypes and globals for wuarray. I put these in their own namespace so they don't conflict with functions in wuparam, wucut, etc.
Function Documentation
void WUArray::analyzeRun (RunInfo & ri, WUArray::RunType runtype)
Analyze a single run.
This is called by process. Right now, it just reads the data and demonstrates some simple things you can do.
Parameters
ri the full run-info struct
runtype - should be process the on, off, or tracking run? These cases may be treated separately.
Definition at line 218 of file wuarray.cpp.
References Image2D::addHistRadially(), HillasParameterization::alpha, RunInfo::arrayconfig, ParamDataReader::getHeaderRecord(), Camera::getNumPixels(), Histogram::increment(), HeaderRecord::nadc, HeaderRecord::num_telescopes, RunInfo::offid, RunInfo::onid, PlotMaker::plotAxes(), HillasParameterization::point_of_origin_a, Image2D::save(), Image2D::setCoordinateBox(), HeaderRecord::sourcename, RunInfo::utdate, Coordinate_t::x, and Coordinate_t::y.
Referenced by process().
void WUArray::getCommandLineOptions (int argc, char ** argv)
This specifies and processes the various command-line options.
See the getopt manpage for more information (type 'man 3 getopt' to see the C documentation, which is in manual section 3).
Definition at line 421 of file wuarray.cpp.
void WUArray::process (RunInfo & ri)
Process a single run.
This is called for each run in the config file.
Definition at line 182 of file wuarray.cpp.
References analyzeRun(), RunInfo::offid, RunInfo::onid, and RunInfo::type.