.TH "AnalysisException" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnalysisException \- 
.PP
Standard exception thrown by analysis routines.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions.h>\fP
.PP
Inherited by \fBCriticalAnalysisException\fP, and \fBMildAnalysisException\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnalysisException\fP (std::string str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Standard exception thrown by analysis routines. 

\fBTodo\fP
.RS 4
: \fBAnalysisException\fP should be a subclass of the STL exception 
.RE
.PP

.PP
Definition at line 21 of file Exceptions.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
