.TH "bug" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
 
.IP "\fBMember \fBHistogram::Histogram\fP(const \fBHistogram\fP &h) \fP" 1c
: doesn't work yet 
.PP
.PP
 
.IP "\fBMember \fBRawDataReaderSim::RawDataReaderSim\fP(const std::string &filename) \fP" 1c
: if file doesn't exist, doesn't always fail! 
.PP

