.TH "ContourSegment" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContourSegment \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCoordinate_t\fP \fBstart\fP"
.br
.ti -1c
.RI "\fBCoordinate_t\fP \fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 226 of file PlotMaker.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
