.TH "Coordinate_t" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coordinate_t \- 
.PP
A 2-d coordinate.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A 2-d coordinate. 
.PP
Definition at line 18 of file Types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
