.TH "Cut" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cut \- 
.PP
Describes range of values of a parameter to retain after cuts.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBlower\fP"
.br
.ti -1c
.RI "double \fBupper\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes range of values of a parameter to retain after cuts. 
.PP
Definition at line 32 of file Config.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
