.TH "CutFactory" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CutFactory \- 
.PP
Responsible for locating files and creating the correct data reader object for the detected file type.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SuperCutter.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSuperCutter\fP * \fBnewCutter\fP (const \fBRunInfo\fP &ri)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCutFactory\fP * \fBinstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsible for locating files and creating the correct data reader object for the detected file type. 

Implemented as a Singleton. 
.PP
Definition at line 139 of file SuperCutter.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
