.TH "CutRecord" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CutRecord \- 
.PP
Output from \fBCutter\fP for each run...  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRecords.h>\fP
.PP
Inherits \fBRecord\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddValuesFrom\fP (\fBCutRecord\fP &cr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBrunid\fP"
.br
.ti -1c
.RI "int \fBtotal\fP"
.br
.ti -1c
.RI "int \fBvalid\fP"
.br
.ti -1c
.RI "int \fBtrigger\fP"
.br
.ti -1c
.RI "int \fBshape\fP"
.br
.ti -1c
.RI "int \fBorientation\fP"
.br
.ti -1c
.RI "int \fBtrackoff\fP"
.br
.ti -1c
.RI "double \fBduration\fP"
.br
.ti -1c
.RI "double \fBaverage_elevation\fP"
.br
.ti -1c
.RI "\fBImage2D\fP \fBim2d\fP"
.br
.ti -1c
.RI "\fBImage2D\fP \fBskybright\fP"
.br
.ti -1c
.RI "\fBImage2D\fP \fBtubeoff\fP"
.br
.ti -1c
.RI "std::vector< \fBCoordinate_t\fP > \fBpoolist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Output from \fBCutter\fP for each run... 
.PP
Definition at line 90 of file DataRecords.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
