.TH "CutRunInfo" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CutRunInfo \- 
.PP
\fBParamRunInfo\fP + cut information.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRecords.h>\fP
.PP
Inherits \fBParamRunInfo\fP.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtotal\fP"
.br
.ti -1c
.RI "int \fBvalid\fP"
.br
.ti -1c
.RI "int \fBtrigger\fP"
.br
.ti -1c
.RI "int \fBshape\fP"
.br
.ti -1c
.RI "int \fBorientation\fP"
.br
.ti -1c
.RI "int \fBtrackoff\fP"
.br
.ti -1c
.RI "double \fBduration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBParamRunInfo\fP + cut information. 
.PP
Definition at line 188 of file DataRecords.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
