.TH "Cuts" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cuts \- 
.PP
Contains enumerations for \fBSuperCutter\fP and related cut objects.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCutMask\fP { \fBSIZE\fP =  1 << 0, \fBMAX\fP =  1 << 1, \fBFRAC\fP =  1 << 2, \fBLENSIZE\fP =  1 << 3, \fBDISTANCE\fP =  1 << 4, \fBLENGTH\fP =  1 << 5, \fBWIDTH\fP =  1 << 6, \fBALPHA\fP =  1 << 7, \fBASYMM\fP =  1 << 8, \fBALL_CUTS\fP =  0xFFFFFFFF }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains enumerations for \fBSuperCutter\fP and related cut objects. 
.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
