.TH "DataReader" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataReader \- 
.PP
Base class for all data readers (raw, parameterized, cut)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataReader.h>\fP
.PP
Inherited by \fBParamDataReader\fP, and \fBRawDataReader\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataReader\fP (const std::string &filename)"
.br
.ti -1c
.RI "std::string \fBgetFilename\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisDone\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBsize\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBgetTypeString\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for all data readers (raw, parameterized, cut) 
.PP
Definition at line 21 of file DataReader.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
