.TH "EnergyEstimator" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnergyEstimator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLZAEnergyEstimator\fP, \fBSZAEnergyEstimator\fP, \fBZ40EnergyEstimator\fP, and \fBZ50EnergyEstimator\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBgetEstimate\fP (const double size, const double distance, const double zenith)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file EnergySpectrum.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
