.TH "EnergySpectrum" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnergySpectrum \- 
.PP
Energy Spectrum 1-D histogram class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EnergySpectrum.h>\fP
.PP
Inherits \fBHistogram\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnergySpectrum\fP (\fBRunInfo\fP &ri, std::string name)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBMIN_COUNTS\fP = 5"
.br
.in -1c
.SH "Detailed Description"
.PP 
Energy Spectrum 1-D histogram class. 
.PP
Definition at line 19 of file EnergySpectrum.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
