.TH "EventRecord" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventRecord \- 
.PP
Event information.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRecords.h>\fP
.PP
Inherits \fBRecord\fP.
.PP
Inherited by \fBRawEventRecord\fP.
.SH "Detailed Description"
.PP 
Event information. 
.PP
Definition at line 58 of file DataRecords.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
