.TH "GaussianDeviate" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GaussianDeviate \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGaussianDeviate\fP (std::string &dbdir)"
.br
.ti -1c
.RI "double \fBgetDeviate\fP ()"
.br
.ti -1c
.RI "double \fBgetFastDeviate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBDBSIZE\fP = 1000000"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file GaussianDeviate.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
