.TH "ImageParameterization" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageParameterization \- 
.PP
Information common to all parameterizations.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImageAnalyzer.h>\fP
.PP
Inherited by \fBHillasParameterization\fP, and \fBMuonParameterization\fP.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBtelescope_id\fP"
.br
.ti -1c
.RI "double \fBosctime\fP"
.br
.ti -1c
.RI "double \fBgpstime\fP"
.br
.ti -1c
.RI "double \fBlivetime\fP"
.br
.ti -1c
.RI "short \fBinvalid\fP"
.br
.ti -1c
.RI "int \fBevent_number\fP"
.br
.ti -1c
.RI "\fBSimShowerRecord\fP \fBsim\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information common to all parameterizations. 
.PP
Definition at line 19 of file ImageAnalyzer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
