.TH "LZAEnergyEstimator" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LZAEnergyEstimator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEnergyEstimator\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetEstimate\fP (const double size, const double distance, const double zenith=1.04719755)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file EnergySpectrum.h.
.SH "Member Function Documentation"
.PP 
.SS "double LZAEnergyEstimator::getEstimate (const doublesize, const doubledist, const doublezenith = \fC1.04719755\fP)\fC [virtual]\fP"
.PP
Energy estimator for LZA (Z ~= 30 degrees) data. This function, which was fit to simulation data, returns the log10 of the estimated energy (log10(EstimatedEnergy)) 
.PP
Implements \fBEnergyEstimator\fP.
.PP
Definition at line 18 of file EnergySpectrum.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
