.TH "MCRecord" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCRecord \- 
.PP
For Each Monte Carlo Event That Passes the Selection \fBCuts\fP, We Want to Know the True Energy and the Reconstructed Energy.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Fitter.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtrueEnergy_in_TeV\fP"
.br
.ti -1c
.RI "double \fBestimatedEnergy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
For Each Monte Carlo Event That Passes the Selection \fBCuts\fP, We Want to Know the True Energy and the Reconstructed Energy. 
.PP
Definition at line 50 of file Fitter.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
