.TH "MildAnalysisException" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MildAnalysisException \- 
.PP
Thrown for warnings and recoverable errors.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions.h>\fP
.PP
Inherits \fBAnalysisException\fP.
.PP
Inherited by \fBEOFException\fP, and \fBRangeException\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMildAnalysisException\fP (const std::string &str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Thrown for warnings and recoverable errors. 
.PP
Definition at line 41 of file Exceptions.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
