.TH "MuonParameterization" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MuonParameterization \- 
.PP
Describes the muon-like characteristics of an image.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MuonImageAnalyzer.h>\fP
.PP
Inherits \fBImageParameterization\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBradius\fP"
.br
.ti -1c
.RI "\fBCoordinate_t\fP \fBringcenter\fP"
.br
.ti -1c
.RI "double \fBarcstrength\fP"
.br
.ti -1c
.RI "double \fBgain\fP"
.br
.ti -1c
.RI "double \fBmugain\fP"
.br
.ti -1c
.RI "double \fBringfrac\fP"
.br
.ti -1c
.RI "double \fBsoal\fP"
.br
.ti -1c
.RI "double \fBmuskew\fP"
.br
.ti -1c
.RI "double \fBarclen\fP"
.br
.ti -1c
.RI "double \fBphilo\fP"
.br
.ti -1c
.RI "double \fBphihi\fP"
.br
.ti -1c
.RI "double \fBphimid\fP"
.br
.ti -1c
.RI "\fBCoordinate_t\fP \fBplot\fP [MAX_PLOT_CENTERS]"
.br
.ti -1c
.RI "int \fBnplotpoints\fP"
.br
.ti -1c
.RI "double \fBmuonness\fP"
.br
.ti -1c
.RI "double \fBsmoothness\fP"
.br
.ti -1c
.RI "double \fBsmoothness_var\fP"
.br
.ti -1c
.RI "double \fBxcs\fP"
.br
.ti -1c
.RI "double \fBycs\fP"
.br
.ti -1c
.RI "double \fBrspread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes the muon-like characteristics of an image. 
.PP
Definition at line 32 of file MuonImageAnalyzer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
