.TH "PairRunInfo" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PairRunInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRunInfo\fP.
.SH "Detailed Description"
.PP 
Definition at line 182 of file Config.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
