.TH "ParamDataWriterNtuple" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParamDataWriterNtuple \- 
.PP
Outputs parameterized events to an N-Tuple (for use in for example, PAW).  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataWriter.h>\fP
.PP
Inherits \fBParamDataWriter\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParamDataWriterNtuple\fP (const std::string &, bool ow=false)"
.br
.ti -1c
.RI "void \fBwriteParameterization\fP (\fBHillasParameterization\fP &)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "std::string \fBgetTypeString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Outputs parameterized events to an N-Tuple (for use in for example, PAW). 
.PP
Definition at line 87 of file DataWriter.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
