.TH "ParseException" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseException \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseException\fP (string what)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file wuplot.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
