.TH "ProgressBar" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgressBar \- 
.PP
Displays a text-based progress bar with estimated time to finish for a particular task.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ProgressBar.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgressBar\fP (int total, std::string name='Progress')"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string name)"
.br
.ti -1c
.RI "void \fBprint\fP (int)"
.br
.ti -1c
.RI "void \fBprintClear\fP ()"
.br
.ti -1c
.RI "double \fBgetTime\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Displays a text-based progress bar with estimated time to finish for a particular task. 
.PP
Definition at line 13 of file ProgressBar.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
