.TH "RawDataReaderHDF4" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RawDataReaderHDF4 \- 
.PP
Implementation of \fBRawDataReader\fP for HDF4 input files.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataReader.h>\fP
.PP
Inherits \fBRawDataReader\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRawDataReaderHDF4\fP (const std::string &filename)"
.br
.ti -1c
.RI "void \fBgetHeaderRecord\fP (\fBRawHeaderRecord\fP &header)"
.br
.ti -1c
.RI "void \fBgetNextEventRecord\fP (\fBRawEventRecord\fP &event)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "bool \fBisDone\fP ()"
.br
.ti -1c
.RI "std::string \fBgetTypeString\fP ()"
.br
.ti -1c
.RI "int \fBgetType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of \fBRawDataReader\fP for HDF4 input files. 
.PP
Definition at line 68 of file DataReader.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
