.TH "RawEventRecord" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RawEventRecord \- 
.PP
One event from a raw data file.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRecords.h>\fP
.PP
Inherits \fBEventRecord\fP.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "double \fBgpstime\fP"
.br
.ti -1c
.RI "double \fBosctime\fP"
.br
.ti -1c
.RI "double \fBlivetime\fP"
.br
.ti -1c
.RI "short \fBelevation\fP"
.br
.ti -1c
.RI "short \fBazimuth\fP"
.br
.ti -1c
.RI "int \fBtelescope_id\fP"
.br
.ti -1c
.RI "Array_t \fBadc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One event from a raw data file. 
.PP
Definition at line 68 of file DataRecords.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
