.TH "RawHeaderRecord" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RawHeaderRecord \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHeaderRecord\fP.
.SH "Detailed Description"
.PP 
Definition at line 83 of file DataRecords.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
