.TH "RawRunInfo" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RawRunInfo \- 
.PP
Header Information read from the raw data.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRecords.h>\fP
.PP
Inherited by \fBParamRunInfo\fP.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBsourcename\fP"
.br
.ti -1c
.RI "std::string \fBrunid\fP"
.br
.ti -1c
.RI "int \fBnadc\fP"
.br
.ti -1c
.RI "double \fBra\fP"
.br
.ti -1c
.RI "double \fBdec\fP"
.br
.ti -1c
.RI "double \fBstarttime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header Information read from the raw data. 
.PP
Definition at line 161 of file DataRecords.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
