.TH "Record" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Record \- 
.PP
Records are readable/writable (i.e.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRecords.h>\fP
.PP
Inherited by \fBCutRecord\fP, \fBEventRecord\fP, and \fBHeaderRecord\fP.
.SH "Detailed Description"
.PP 
Records are readable/writable (i.e. 

serializable) representations of data. For example, a \fBDataReader\fP should read data from a file and return a \fBRecord\fP for each event read; the corresponding \fBDataWriter\fP would write a \fBRecord\fP to disk. 
.PP
Definition at line 18 of file DataRecords.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
