.TH "RunStatistics" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RunStatistics \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBsignificance\fP"
.br
.ti -1c
.RI "double \fBexcess\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file Cutter.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
