.TH "SimShowerRecord" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimShowerRecord \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBevent_number\fP"
.br
.ti -1c
.RI "int \fBprimary_type\fP"
.br
.ti -1c
.RI "double \fBprimary_energy\fP"
.br
.ti -1c
.RI "\fBCoordinate_t\fP \fBimpact_parameter\fP"
.br
.ti -1c
.RI "\fBCoordinate_t\fP \fBdirection_cos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file DataRecords.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
