.TH "Star" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Star \- 
.PP
representation of a star  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StarCatalog.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBspectclass\fP"
.br
.ti -1c
.RI "double \fBra\fP"
.br
.ti -1c
.RI "double \fBdec\fP"
.br
.ti -1c
.RI "double \fBmagnitude\fP"
.br
.ti -1c
.RI "int \fBepoch\fP"
.br
.ti -1c
.RI "double \fBora\fP"
.br
.ti -1c
.RI "double \fBodec\fP"
.br
.ti -1c
.RI "double \fBtx\fP"
.br
.ti -1c
.RI "double \fBty\fP"
.br
.ti -1c
.RI "int \fBcatalog_id\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBStar\fP &s1, const \fBStar\fP &s2)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBStar\fP &s1, const \fBStar\fP &s2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBStar\fP &s1, const \fBStar\fP &s2)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBStar\fP &s1, const \fBStar\fP &s2)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &stream, \fBStar\fP &s)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &stream, \fBStar\fP &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
representation of a star 
.PP
Definition at line 11 of file StarCatalog.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
