.TH "TelescopeArray::TelInfo" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TelescopeArray::TelInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "\fBCamera\fP * \fBcam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file Camera.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
