.TH "ThresholdImageCleaner" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThresholdImageCleaner \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBImageCleaner\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThresholdImageCleaner\fP (\fBCamera\fP &camera, double threshold)"
.br
.ti -1c
.RI "std::vector< int > & \fBgetCleanPixels\fP (const Array_t &image)"
.br
.ti -1c
.RI "void \fBsetThreshold\fP (double t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file ImageCleaner.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
