.TH "Z50EnergyEstimator" 3 "Tue Nov 1 2011" "Version 0.1" "wuparam" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Z50EnergyEstimator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEnergyEstimator\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetEstimate\fP (const double size, const double distance, const double zenith=0.872664)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file EnergySpectrum.h.
.SH "Member Function Documentation"
.PP 
.SS "double Z50EnergyEstimator::getEstimate (const doublesize, const doubledist, const doublezenith = \fC0.872664\fP)\fC [virtual]\fP"
.PP
Energy estimator for SZA (Z ~= 50 degrees) data. This function, which was fit to simulation data, returns the log10 of the estimated energy (log10(EstimatedEnergy)) 
.PP
Implements \fBEnergyEstimator\fP.
.PP
Definition at line 227 of file EnergySpectrum.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for wuparam from the source code.
